-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-08-10 16:31:25 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



CREATE TABLE employee (
    e_id            NUMBER(3) NOT NULL,
    e_fname         VARCHAR2(30 CHAR) NOT NULL,
    e_lname         VARCHAR2(30 CHAR) NOT NULL,
    e_email         VARCHAR2(50) NOT NULL,
    e_phone         VARCHAR2(20) NOT NULL,
    e_street        VARCHAR2(50) NOT NULL,
    e_suburb        VARCHAR2(30) NOT NULL,
    e_postcode      VARCHAR2(4) NOT NULL,
    e_gender        VARCHAR2(1) NOT NULL,
    date_employed   DATE NOT NULL
);

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( e_id );

CREATE TABLE movie (
    movie_id              NUMBER(4) NOT NULL,
    movie_title           VARCHAR2(100) NOT NULL,
    movie_rating          VARCHAR2(100) NOT NULL,
    movie_released_date   DATE NOT NULL,
    movie_description     VARCHAR2(500),
    movie_length          NUMBER(3) NOT NULL
);

ALTER TABLE movie ADD CONSTRAINT movie_pk PRIMARY KEY ( movie_id );

CREATE TABLE screening (
    screening_id           NUMBER(6) NOT NULL,
    screening_date         DATE NOT NULL,
    screening_start_hh24   NUMBER(2) NOT NULL,
    screening_start_mm60   NUMBER(2) NOT NULL,
    plan_id                NUMBER(4) NOT NULL,
    theatre_id             NUMBER(1) NOT NULL
);

ALTER TABLE screening ADD CONSTRAINT screening_pk PRIMARY KEY ( screening_id );

CREATE TABLE screening_plan (
    plan_id                 NUMBER(4) NOT NULL,
    plan_start_date         DATE NOT NULL,
    plan_end_date           DATE,
    plam_min_start_hh24     NUMBER(2) NOT NULL,
    plan_max_start_hh24     NUMBER(2) NOT NULL,
    plan_no_of_screenings   NUMBER(2) NOT NULL,
    movie_id                NUMBER(4) NOT NULL
);

ALTER TABLE screening_plan ADD CONSTRAINT screening_plan_pk PRIMARY KEY ( plan_id );

CREATE TABLE seat (
    seat_id       NUMBER(5) NOT NULL,
    seat_number   NUMBER(3) NOT NULL,
    row_id        NUMBER(4) NOT NULL
);

ALTER TABLE seat ADD CONSTRAINT seat_pk PRIMARY KEY ( seat_id );

CREATE TABLE  theatre_row (
    row_id            NUMBER(4) NOT NULL,
    row_name          VARCHAR2(2) NOT NULL,
    row_total_seats   NUMBER(3) NOT NULL,
    theatre_id        NUMBER(1) NOT NULL
);

ALTER TABLE  theatre_row ADD CONSTRAINT  theatre_row_pk PRIMARY KEY ( row_id );

CREATE TABLE theatre (
    theatre_id            NUMBER(1) NOT NULL,
    theater_description   NVARCHAR2(100),
    theatre_total_rows    NUMBER(3) NOT NULL
);

ALTER TABLE theatre ADD CONSTRAINT theatre_pk PRIMARY KEY ( theatre_id );

CREATE TABLE ticket (
    ticket_id      NUMBER(8) NOT NULL,
    ticket_date    DATE NOT NULL,
    t_type_id      NUMBER(1) NOT NULL,
    seat_id        NUMBER(5) NOT NULL,
    screening_id   NUMBER(6) NOT NULL
);

ALTER TABLE ticket ADD CONSTRAINT ticket_pk PRIMARY KEY ( ticket_id );

CREATE TABLE ticket_type (
    t_type_id           NUMBER(1) NOT NULL,
    t_type              VARCHAR2(20 CHAR) NOT NULL,
    t_type_price        NUMBER(4, 2) NOT NULL,
    t_type_start_date   DATE NOT NULL,
    t_type_end_date     DATE
);

ALTER TABLE ticket_type ADD CONSTRAINT ticket_type_pk PRIMARY KEY ( t_type_id );

ALTER TABLE screening_plan
    ADD CONSTRAINT screening_plan_movie_fk FOREIGN KEY ( movie_id )
        REFERENCES movie ( movie_id );

ALTER TABLE screening
    ADD CONSTRAINT screening_screening_plan_fk FOREIGN KEY ( plan_id )
        REFERENCES screening_plan ( plan_id );

ALTER TABLE screening
    ADD CONSTRAINT screening_theatre_fk FOREIGN KEY ( theatre_id )
        REFERENCES theatre ( theatre_id );

ALTER TABLE seat
    ADD CONSTRAINT seat_theatere_row_fk FOREIGN KEY ( row_id )
        REFERENCES  theatre_row ( row_id );

ALTER TABLE  theatre_row
    ADD CONSTRAINT  theatre_row_theatre_fk FOREIGN KEY ( theatre_id )
        REFERENCES theatre ( theatre_id );

ALTER TABLE ticket
    ADD CONSTRAINT ticket_screening_fk FOREIGN KEY ( screening_id )
        REFERENCES screening ( screening_id );

ALTER TABLE ticket
    ADD CONSTRAINT ticket_seat_fk FOREIGN KEY ( seat_id )
        REFERENCES seat ( seat_id );

ALTER TABLE ticket
    ADD CONSTRAINT ticket_ticket_type_fk FOREIGN KEY ( t_type_id )
        REFERENCES ticket_type ( t_type_id );

ALTER TABLE  theatre
    ADD CONSTRAINT check_theatreID CHECK(theatre_id BETWEEN 1 AND 5)
    ADD CONSTRAINT check_rows CHECK(theatre_total_rows BETWEEN 1 AND 26);
    
ALTER TABLE Theatre_Row
    ADD CONSTRAINT check_RowID CHECK(row_id>0)
    ADD CONSTRAINT check_RowName CHECK(row_name BETWEEN 'A' AND 'Z')
    ADD CONSTRAINT check_SeatTotal CHECK(row_total_seats>=1)
    ADD CONSTRAINT chk_UniqTheatreRowName UNIQUE (theatre_id, row_name);
    
ALTER TABLE Seat
    ADD CONSTRAINT check_SeatID CHECK(seat_id>0)
    ADD CONSTRAINT check_SeatNum CHECK(seat_number>=1)
    ADD CONSTRAINT check_UniqTheatreSeatID UNIQUE (row_id, seat_number);
    
ALTER TABLE Movie 
    ADD CONSTRAINT check_MovieID CHECK(movie_id>0)
    ADD CONSTRAINT check_Rating CHECK(movie_rating in ('G','PG','PG-13','M','MA15+','R18+'))
    MODIFY movie_released_date DEFAULT SYSDATE; 

ALTER TABLE Screening_Plan
    ADD CONSTRAINT check_PlanID CHECK(plan_id>0)
    ADD CONSTRAINT check_MinStart CHECK(plam_min_start_hh24 BETWEEN 9 AND 22)
    ADD CONSTRAINT check_MaxStart  CHECK(plan_max_start_hh24 BETWEEN 9 AND 22 AND plan_max_start_hh24>=plam_min_start_hh24)
    ADD CONSTRAINT check_NoScreen CHECK(plan_no_of_screenings>=1)
    ADD CONSTRAINT check_UniqMvIDStartDate UNIQUE (movie_id, plan_start_date)
    MODIFY plan_start_date DEFAULT NEXT_DAY(SYSDATE,'MON')
    MODIFY plan_end_date DEFAULT (NEXT_DAY(SYSDATE,'MON')+6)
    MODIFY plam_min_start_hh24 DEFAULT 9
    MODIFY plan_max_start_hh24 DEFAULT 22;
    
ALTER TABLE Screening
    ADD CONSTRAINT check_screenID CHECK(screening_id>0)
    ADD CONSTRAINT check_StartHrs CHECK(screening_start_hh24 between 9  AND 22)
    ADD CONSTRAINT check_StartMin CHECK(screening_start_mm60 between 0  AND 59)
    ADD CONSTRAINT check_UniqScreening  UNIQUE (theatre_id, screening_date, screening_start_hh24, screening_start_mm60)
    MODIFY screening_date DEFAULT SYSDATE;
    
ALTER TABLE Ticket_Type
    ADD CONSTRAINT check_TypeID CHECK(t_type_id>0)
    ADD CONSTRAINT check_TypePrice CHECK(t_type_price> 0)
    ADD CONSTRAINT check_ENDDATE CHECK(t_type_end_date IS NULL OR t_type_end_date>t_type_start_date)
    ADD CONSTRAINT check_UniqTicketType  UNIQUE (t_type, t_type_start_date);
   
ALTER TABLE Ticket
    ADD CONSTRAINT check_TicketID CHECK(ticket_id>0)
    ADD CONSTRAINT check_uniqTicket UNIQUE(screening_id, seat_id)
    MODIFY ticket_date DEFAULT SYSDATE;

ALTER TABLE Employee
    ADD CONSTRAINT check_e_ID CHECK(e_id>0)
    ADD CONSTRAINT check_Email CHECK(e_email LIKE '%@%.%')
    ADD CONSTRAINT check_POSTCODE CHECK(e_postcode between 0200 AND 9999)
    ADD CONSTRAINT check_gender CHECK(E_GENDER IN ('M','F','m','f'))
    ADD CONSTRAINT check_UniqEmp UNIQUE (e_fname, e_lname)
    ADD CONSTRAINT check_UniqEmail UNIQUE (e_email)
    MODIFY date_employed DEFAULT SYSDATE;
    
-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
