# Generated by Django 2.2.3 on 2019-09-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonCompleting', models.CharField(max_length=250)),
                ('Date', models.DateField(auto_now_add=True)),
                ('TimeIncidentStarted', models.DateTimeField(blank=True, null=True)),
                ('TimeIncedentEnded', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wakingup', models.CharField(max_length=255)),
                ('pain', models.CharField(max_length=255)),
                ('staff', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
                ('Date_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Date_time')),
            ],
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason1', models.CharField(max_length=255)),
                ('reason2', models.CharField(max_length=255)),
                ('reason3', models.CharField(max_length=255)),
                ('reason4', models.CharField(max_length=255)),
                ('reason5', models.CharField(max_length=255)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='CuesOfDistress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cues1', models.CharField(max_length=255)),
                ('cues2', models.CharField(max_length=255)),
                ('cues3', models.CharField(max_length=255)),
                ('cues4', models.CharField(max_length=255)),
                ('cues5', models.CharField(max_length=255)),
                ('cues6', models.CharField(max_length=255)),
                ('Triggers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Triggers')),
            ],
        ),
    ]
