# Generated by Django 2.2.4 on 2019-09-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuesofdistress',
            name='Triggers',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Date_time',
        ),
        migrations.RemoveField(
            model_name='triggers',
            name='Location',
        ),
    ]
