# Generated by Django 2.2.4 on 2019-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190904_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuesofdistress',
            name='cues_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='Date_time_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='triggers',
            name='Location_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
