# Generated by Django 3.0.1 on 2020-01-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='ChartValue',
        ),
    ]
